#!/bin/bash

#This Script is to Auto install

#Update as Root
sudo apt-get update
echo Update Done

#Upgrade as Root
sudo apt-get upgrade -y
echo Upgrade Done

#Install Conky
sudo apt-get install conky -y
echo Conky Installed

#Conky Settings File
wget -O /home/pi/.conkyrc https://raw.githubusercontent.com/novaspirit/rpi_conky/master/rpi3_conkyrc
echo Downloaded Conky Settings

#Create Conky Shell Script
sudo printf '#!/bin/sh\n(sleep 4s && conky) &\nexit 0' > /usr/bin/conky.sh

#Create the conky.desktop file for the autostart process
printf '[Desktop Entry]\nName=conky\nType=Application\nExec=sh /usr/bin/conky.sh\nTerminal=false\nComment=system monitoring tool.\nCategories=Utility;' > /etc/xdg/autostart/conky.desktop
echo Conky is Installed

#Install WBar
sudo apt-get install wbar wbar-config -y
echo WBAR is Installed, Time to Reboot



#Reboot

